### ISSUE TITLE
Add macOS to the build matrix

### ISSUE THREAD

**Issue by vreuter** [pepkit/ubiquerg#10]
Travis now appears to have [macOS build capability](https://docs.travis-ci.com/user/reference/osx/). We should include this in our build matrix to get some Mac testing, for things that may be OS-specific:
https://github.com/pepkit/ubiquerg/issues/9#issuecomment-498332895

**Comment by nsheff** [comment]
building on macos take forever and it's not really my priority at this point. feel free to reopen if you want to investigate this further.
