### ISSUE TITLE
NameError; is_writable

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/ubiquerg#16]
```
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/system.py", line 54, in is_writable
    return is_writeable(os.path.dirname(folder), check_exist)
NameError: name 'is_writeable' is not defined
```

**Comment by nsheff** [comment]
it should be named is_writable, not is_writeable

**Comment by nsheff** [comment]
https://github.com/pepkit/ubiquerg/commit/5926bb1da2baa5bccb93480368ec5bef9f7de8c2

**Comment by stolarczyk** [comment]
that's right. The thing is this commit changed just the function name, but it is used again in the return statement
