### ISSUE TITLE
isolate testing

### ISSUE THREAD

**Issue by nsheff** [pepkit/ubiquerg#2]
Right now the package requires pytest. This causes docs builds for all packages that use ubiquerg to require installing pytest. We should isolate this dependency to only testing.

See: https://github.com/pepkit/geofetch/commit/ab2c03a93a44bb658aad5bd6ef0c718bab223710

**Comment by vreuter** [comment]
I don't understand...`ExpectContext` is _tested_ within this package, but it's not _used by_ tests in this package; it's intended for import by other packages.

**Comment by nsheff** [comment]
Ok, I'm confused. I can't understand all the pytest stuff, it's too complicated for me. All I'm trying to do is fix this error:

https://readthedocs.org/projects/geofetch/builds/9035929/

And I don't think adding `pytest` to requirements.txt is the solution, because I don't think RTD should have to install pytest.

**Comment by vreuter** [comment]
The build should resolve itself once `geofetch` master is released, without changing the reqs file, as I think [what you suggested](https://github.com/pepkit/peppy/commit/8eddb27eebbeb077ebd5d8d1bee3991c8bf0f7f6#commitcomment-33395348) worked in `peppy`, right?

**Comment by nsheff** [comment]
ah... but this is different because it just depends on the next ubiquerg release then, right? if you added a pytest dependency to ubiquerg?

**Comment by nsheff** [comment]
as an aside, though, wouldn't you rather *not* have pytest as a general dependency of a package and only have it as a test dependency?

**Comment by vreuter** [comment]
Not particularly...I think `pytest` is only slightly less central/integral than something like `setuptools`, and is therefore something that should essentially always be installed. That said, this sort of question is what initially motivated separate/sub installations in `pypiper`, basically for more granular user installation options according to desired use of `ngstk`, so is something that could be considered here. Again, though, I mostly think that `pytest` should virtually always be installed.
