### ISSUE TITLE
Path expansions: separate concerns

### ISSUE THREAD

**Issue by vreuter** [pepkit/ubiquerg#24]
Don't deal with double slashes so far upstream; defer responsbility to more user-proximal code.

**Comment by vreuter** [comment]
https://github.com/pepkit/ubiquerg/blob/master/ubiquerg/paths.py#L21

**Comment by vreuter** [comment]
https://github.com/pepkit/attmap/issues/64

**Comment by nsheff** [comment]
For reference, here's the content of the yaml file that's getting altered:

```
  - command: libre
    docker_image: nsheff/libreoffice
    docker_command: "libreoffice -env:UserInstallation=file:///tmp/ -env:SingleAppInstance='false'"
```
it's a bulker manifest. I can solve it by putting 6 slashes in instead of 3...

**Comment by mikekaganski** [comment]
> -env:SingleAppInstance='false'

Please don't use random switches as a cargo cult. The "SingleAppInstance" is not a LibreOffice environment variable of any kind. It is a config option of PortableApps launcher, so only applicable to that Windows executable; and in no case, would that configuration (intended to be in an INI file of that launcher) work in the '-env:' command line argument passed to LibreOffice. But there seems to be a growing number of this misguided nonsense in different related discussions.
