### ISSUE TITLE
`is_command_callable` is failing on windows

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/ubiquerg#37]
geofetch is using this function, to check if prefetch is installed on the computer. 
For users, who are using windows, this command is failing.

**Comment by nsheff** [comment]
I'm not that interested in supporting windows in general. If we can support windows easily, then fine, but at this point, I am not interested in investing a lot of time to make things work on windows.

**Comment by khoroshevskyi** [comment]
Windows support was added to this particular function. It was tested only once, and no Windows test suites were added, which means we cannot ensure compatibility with Windows. Therefore, I'm closing this issue.
