### ISSUE TITLE
query_yes_no raises a NameError on a valid answer

### ISSUE THREAD

**Issue by stolarczyk** [pepkit/ubiquerg#9]
see: https://github.com/databio/refgenconf/pull/19#pullrequestreview-244943052

**Comment by stolarczyk** [comment]
when I hit Enter with no answer:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/refgenie", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenie/refgenie.py", line 360, in main
    rgc.pull_asset(args.genome, args.asset, genome_config_path, args.unpack)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in pull_asset
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 188, in <listcomp>
    genome, a, genome_config, unpack, get_json_url, get_main_url) for a in assets]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/refgenconf/refgenconf.py", line 220, in _pull_asset
    query_yes_no("Are you sure you want to download this large archive?"):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 66, in query_yes_no
    return parse(_read_from_user() or default)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py", line 72, in _read_from_user
    return eval(input())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

**Comment by vreuter** [comment]
~~3.6-specific~~ -- different key combo

**Comment by vreuter** [comment]
@michalstolarczyk  This looks like a `SyntaxError` rather than `NameError`...?

**Comment by stolarczyk** [comment]
`NameError` is raised [here](https://github.com/databio/refgenconf/pull/19#pullrequestreview-244943052)

my comment shows another or related problem, I just didn't want to open another issue for that

**Comment by vreuter** [comment]
OK, good idea. I'm going to open these as a single issue in `refgenie`, because these aren't reproducible for me with just `ubiquerg`:
```
master└─ $ ipython
^[[APython 3.6.8 (default, Dec 24 2018, 19:24:27) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from ubiquerg import query_yes_no                                                                                                                                                                   

In [2]: query_yes_no("what")                                                                                                                                                                                
what [y/N] y
Out[2]: True

In [3]: query_yes_no("what")                                                                                                                                                                                
what [y/N] 
Out[3]: False
```

**Comment by stolarczyk** [comment]
oh, now I see that this is specific to Python 3.6.5 and/or macOS:
```
[mstolarczyk@MichalsMBP refgenieserver]: ipy
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from ubiquerg import query_yes_no                                              

In [2]: query_yes_no("what")                                                           
what [y/N] y
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-8b68b4d130ea> in <module>
----> 1 query_yes_no("what")

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in query_yes_no(question, default)
     64         sys.stdout.write(msg)
     65         try:
---> 66             return parse(_read_from_user() or default)
     67         except KeyError:
     68             sys.stdout.write("Please respond with 'yes' or 'no' (or 'y' or 'n').\n")

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in _read_from_user()
     70 
     71 def _read_from_user():
---> 72     return eval(input())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in <module>

NameError: name 'y' is not defined
```
since it worked for me on Rivanna using Python 3.6.6

**Comment by vreuter** [comment]
> OK, good idea. I'm going to open these as a single issue in `refgenie`, because these aren't reproducible for me with just `ubiquerg`:
> 

Now open as https://github.com/databio/refgenie/issues/35

**Comment by vreuter** [comment]
> oh, now I see that this is specific to Python 3.6.5 and/or macOS:
> 
> ```
> [mstolarczyk@MichalsMBP refgenieserver]: ipy
> Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: from ubiquerg import query_yes_no                                              
> 
> In [2]: query_yes_no("what")                                                           
> what [y/N] y
> ---------------------------------------------------------------------------
> NameError                                 Traceback (most recent call last)
> <ipython-input-2-8b68b4d130ea> in <module>
> ----> 1 query_yes_no("what")
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in query_yes_no(question, default)
>      64         sys.stdout.write(msg)
>      65         try:
> ---> 66             return parse(_read_from_user() or default)
>      67         except KeyError:
>      68             sys.stdout.write("Please respond with 'yes' or 'no' (or 'y' or 'n').\n")
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in _read_from_user()
>      70 
>      71 def _read_from_user():
> ---> 72     return eval(input())
> 
> /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ubiquerg/cli_tools.py in <module>
> 
> NameError: name 'y' is not defined
> ```
> 
> since it worked for me on Rivanna using Python 3.6.6

Interesting...so it worked for you on Rivanna even in the `refgenie` context, not just doing the call directly in `ubiquerg`?

**Comment by stolarczyk** [comment]
Did not test it in that context before. But it is failing and raises the same errors.

**Comment by vreuter** [comment]
> Did not test it in that context before. But it is failing and raises the same errors.

What's "it?" 4 cases are of interest; can you clarify which of these raise errors?
- [ ] local on OSX, as just `ubiquerg`
- [ ] local on OSX, as `refgenie`
- [ ] Rivanna, as just `ubiquerg`
- [ ] Rivanna, as `refgenie`

**Comment by stolarczyk** [comment]
Failing: 

- macOS with `refgenie`
- Rivanna with `refgenie`

I just fixed the "macOS as just `ubiquerg`" by running `pip uninstall ubiquerg` and then `pip install ubiquerg` rather than just the latter (which has never been an issue in this regard)

Soo.. the `refgenie` context is the only problem now

**Comment by vreuter** [comment]
I can confirm `ubiquerg` by itself works on Rivanna, using 0.4.0 and Python 2.7.15:
```
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ubiquerg
>>> ubiquerg.query_yes_no("what?")
what? [y/N] y
True
>>> ubiquerg.query_yes_no("what?")
what? [y/N] 
False
>>> ubiquerg.__version__
'0.4'
>>> 

```

**Comment by vreuter** [comment]
> Failing:
> 
>     * macOS with `refgenie`
> 
>     * Rivanna with `refgenie`
> 
> 
> I just fixed the "macOS as just `ubiquerg`" by running `pip uninstall ubiquerg` and then `pip install ubiquerg` rather than just the latter (which has never been an issue in this regard)
> 
> Soo.. the `refgenie` context is the only problem now

OK, thanks for clarifying!
